load("@com_alwaldend_com_github_infinitimeorg_infinitime_pip//:requirements.bzl", "all_requirements")
load("@rules_pkg//pkg:mappings.bzl", "pkg_files", "strip_prefix")
load("@rules_python//python:py_binary.bzl", "py_binary")

py_binary(
    name = "lv_img_conv",
    srcs = ["lv_img_conv.py"],
    visibility = ["//:__pkg__"],
    deps = all_requirements,
)

pkg_files(
    name = "srcs",
    srcs = glob(
        ["**"],
        exclude = ["**/BUILD.bazel"],
    ),
    prefix = package_name(),
    strip_prefix = strip_prefix.from_pkg(),
    visibility = ["//:__pkg__"],
)
