load("@bazel_skylib//rules:write_file.bzl", "write_file")

write_file(
    name = "patches",
    out = "patches.sh",
    content = [
        "#!/usr/bin/env sh",
        "set -eux",
        'cd "${BUILD_WORKSPACE_DIRECTORY}"',
        "git diff --check 1.15.0",
        "git diff \
            1.15.0 \
            >../src/projects/infinitime/main/patch/patch.patch \
        ",
    ],
    is_executable = True,
)
