load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@com_alwaldend_com_github_infinitimeorg_infinitime_npm//:defs.bzl", "npm_link_all_packages")
load("@rules_pkg//pkg:mappings.bzl", "pkg_filegroup", "pkg_files", "strip_prefix")
load("//bazel/bzl:build_binary.bzl", "build_binary")
load("//bazel/bzl:build_run_binary.bzl", "build_run_binary")

write_file(
    name = "patches",
    out = "patches.sh",
    content = [
        "#!/usr/bin/env sh",
        "set -eux",
        'cd "${BUILD_WORKSPACE_DIRECTORY}"',
        "git diff --check 1.15.0",
        "git diff \
            --cached \
            1.15.0 \
            >../src/projects/infinitime/main/patch/patch.patch \
        ",
    ],
    is_executable = True,
)

genrule(
    name = "dfu",
    srcs = [":build"],
    outs = ["pinetime-mcuboot-app-dfu-1.15.0.zip"],
    cmd = """
        cp $(execpath :build)/src/pinetime-mcuboot-app-dfu-1.15.0.zip \
            $(execpath pinetime-mcuboot-app-dfu-1.15.0.zip)
    """,
    visibility = ["//visibility:public"],
)

build_run_binary(
    name = "build",
    binary = ":build_binary",
)

build_binary(
    name = "build_binary",
    srcs = [":srcs"],
)

build_binary(
    name = "build_binary_dev",
    arguments = [
        "--src_dir",
        "${BUILD_WORKSPACE_DIRECTORY}",
        "--build_dir",
        "${BUILD_WORKSPACE_DIRECTORY}/out",
    ],
)

pkg_filegroup(
    name = "srcs",
    srcs = [
        ":srcs_files",
        "//src/resources:srcs",
        "//tools/mcuboot:srcs",
    ],
)

pkg_files(
    name = "srcs_files",
    srcs = glob(
        ["**"],
        exclude = ["compile_commands.json"],
    ),
    strip_prefix = strip_prefix.from_pkg(),
)

npm_link_all_packages(
    name = "node_modules",
)

exports_files(
    ["LICENSE"],
    visibility = ["//visibility:public"],
)
